// @flow
export const BUCKET_OBJECT_SAVE = 'BUCKET_OBJECT_SAVE';
export const BUCKET_OBJECT_REMOVE = 'BUCKET_OBJECT_REMOVE';
export const GHOST_SAVE = 'GHOST_SAVE';
export const GHOST_REMOVE = 'GHOST_REMOVE';
export const BUCKET_QUEUE_CHANGE = 'BUCKET_QUEUE_CHANGE';
